jobs:
- name: update-eirinifs
  plan:
  - get: eirinifs
    trigger: true
  - get: cflinuxfs2-image
    trigger: true
  - get: eirinifs-version
    params:
      bump: major
  - put: eirinifs-version
    params:
      file: eirinifs-version/version
  - task: build eirinifs
    privileged: true
    file: eirinifs/ci/build-eirinifs.yml
  - put: eirinifs-release
    params:
      name: eirinifs-version/version
      tag: eirinifs-version/version
      tag_prefix: v
      globs:
      - go/src/github.com/cloudfoundry-incubator/eirinifs/image/eirinifs.tar

resources:
- name: eirinifs
  type: git
  source:
    uri: https://github.com/gdankov/eirinifs.git
    branch: master
- name: cflinuxfs2-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs2
- name: eirinifs-release
  type: github-release
  source:
    owner: gdankov
    repository: eirinifs
    access_token: ((github-access-token))
- name: eirinifs-version
  type: semver
  source:
    driver: git
    uri: git@github.com:cloudfoundry/eirini-private-config.git
    branch: eirinifs-release-version
    file: version
    private_key: ((github-private-key))

